# Generated by Django 6.0.3 on 2026-03-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidayCode', models.CharField(max_length=20)),
                ('holidayName', models.CharField(max_length=50)),
                ('holidayDate', models.DateField(max_length=20)),
                ('holidayType', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_holiday',
            },
        ),
    ]
