# Generated by Django 6.0.3 on 2026-03-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0004_plantnursery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantName', models.CharField(max_length=50)),
                ('eventName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('registrationDate', models.DateField(max_length=15)),
            ],
            options={
                'db_table': 'sos_event',
            },
        ),
    ]
