# Generated by Django 6.0.3 on 2026-03-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewardCode', models.CharField(max_length=50)),
                ('rewardName', models.CharField(max_length=50)),
                ('rewardAmount', models.CharField(max_length=50)),
                ('rewardStatus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_reward',
            },
        ),
    ]
