# Generated by Django 6.0.3 on 2026-03-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0006_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejectionCode', models.CharField(max_length=50)),
                ('requestName', models.CharField(max_length=50)),
                ('rejectionReason', models.CharField(max_length=50)),
                ('rejectionStatus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_rejection',
            },
        ),
    ]
