# Generated by Django 6.0.3 on 2026-03-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0007_rejection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorName', models.CharField(max_length=50)),
                ('bloodGroup', models.CharField(max_length=10)),
                ('donationDate', models.DateField(max_length=15)),
                ('contactNumber', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'sos_blood_donation',
            },
        ),
    ]
