# Generated by Django 6.0.3 on 2026-04-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0008_blooddonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffName', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_security',
            },
        ),
    ]
