# Generated by Django 6.0.3 on 2026-04-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0009_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateCode', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_notification_template',
            },
        ),
    ]
