# Generated by Django 6.0.3 on 2026-04-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0010_notificationtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limitCode', models.CharField(max_length=50)),
                ('limitName', models.CharField(max_length=30)),
                ('maxValue', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_limit',
            },
        ),
    ]
