# Generated by Django 6.0.3 on 2026-04-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0011_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purgeCode', models.CharField(max_length=30)),
                ('dataType', models.CharField(max_length=30)),
                ('lastRunDate', models.DateField(max_length=20)),
                ('status', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'sos_purge',
            },
        ),
    ]
