# Generated by Django 6.0.3 on 2026-04-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0012_purge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campName', models.CharField(max_length=30)),
                ('campDate', models.DateField(max_length=20)),
                ('organizer', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_donationcamp',
            },
        ),
    ]
