# Generated by Django 6.0.3 on 2026-05-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0013_donationcamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountCode', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=30)),
                ('accountType', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_account',
            },
        ),
    ]
