# Generated by Django 6.0.3 on 2026-05-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0014_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energySource', models.CharField(max_length=50)),
                ('productionUnit', models.CharField(max_length=30)),
                ('outputLevel', models.CharField(max_length=50)),
                ('efficiencyRate', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sos_energy',
            },
        ),
    ]
