# Generated by Django 6.0.3 on 2026-05-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0015_energy'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historyCode', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=30)),
                ('loginTime', models.DateField(max_length=15)),
                ('status', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'sos_loginhistory',
            },
        ),
    ]
