# Generated by Django 6.0.3 on 2026-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0016_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='loginTime',
            field=models.TimeField(max_length=15),
        ),
    ]
