# Generated by Django 6.0.3 on 2026-03-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=50)),
                ('membershipType', models.CharField(max_length=30)),
                ('startDate', models.DateField(max_length=20)),
                ('endDate', models.DateField(max_length=20)),
            ],
            options={
                'db_table': 'sos_gym',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loanAmount', models.CharField(max_length=50)),
                ('interestRate', models.CharField(max_length=50)),
                ('issueDate', models.DateField(max_length=20)),
            ],
            options={
                'db_table': 'sos_loan',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'sos_role',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelerName', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('startDate', models.DateField(max_length=20)),
                ('endDate', models.DateTimeField(max_length=20)),
            ],
            options={
                'db_table': 'sos_travel',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('loginId', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('confirmPassword', models.CharField(max_length=20)),
                ('dob', models.DateField(max_length=20)),
                ('address', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=30)),
                ('mobileNumber', models.CharField(default='', max_length=30)),
                ('roleId', models.IntegerField()),
                ('roleName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_user',
            },
        ),
    ]
