# Generated by Django 6.0.3 on 2026-03-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0002_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speakerName', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=60)),
                ('organization', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sos_speaker',
            },
        ),
    ]
