# Generated by Django 6.0.3 on 2026-03-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orsapi', '0003_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantNursery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantName', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sos_plant_nursery',
            },
        ),
    ]
